apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rdv-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/M4STERPIECE77K/MED-MANAGE.git
    targetRevision: develop
    path: backend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: rdv-dev
